services:
  api:
    image: hard-brain-api 
    build:
      context: ./hard-brain-api
      dockerfile: Dockerfile
    env_file: ./postgres_password.env
    environment:
      PORT: 8000
      PGUSER: "postgres"
      POSTGRES_DB: "hard-brain-db"
      DB_HOSTNAME: "db"
    ports:
      - '8000:8000'
    restart: always

  bot:
    image: hard-brain-bot
    build:
      context: ./hard-brain-bot
      dockerfile: Dockerfile
    env_file:
      - ./postgres_password.env
      - ./discord_token.env
    environment:
      HARD_BRAIN_API_HOSTNAME: "172.17.0.1" # host.docker.internal

  db:
    image: postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 2s
      timeout: 10s
      retries: 10
    env_file: ./postgres_password.env
    environment:
      PGUSER: "postgres"
      POSTGRES_DB: "hard-brain-db"
      DB_HOSTNAME: "db"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
